version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: donizo
      POSTGRES_PASSWORD: donizo
      POSTGRES_DB: pricing
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U donizo -d pricing"]
      interval: 5s
      timeout: 5s
      retries: 20
  api:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://donizo:donizo@db:5432/pricing
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CONFIG_PATH: /app/config.yaml
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
